//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthenticationWCF.Validator {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://facade.validator.cesi.com/", ConfigurationName="Validator.ValidatorEndpoint")]
    public interface ValidatorEndpoint {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément msg de l'espace de noms  n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://facade.validator.cesi.com/ValidatorEndpoint/validatorOperationRequest", ReplyAction="http://facade.validator.cesi.com/ValidatorEndpoint/validatorOperationResponse")]
        AuthenticationWCF.Validator.validatorOperationResponse validatorOperation(AuthenticationWCF.Validator.validatorOperationRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validatorOperationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validatorOperation", Namespace="http://facade.validator.cesi.com/", Order=0)]
        public AuthenticationWCF.Validator.validatorOperationRequestBody Body;
        
        public validatorOperationRequest() {
        }
        
        public validatorOperationRequest(AuthenticationWCF.Validator.validatorOperationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class validatorOperationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string msg;
        
        public validatorOperationRequestBody() {
        }
        
        public validatorOperationRequestBody(string msg) {
            this.msg = msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validatorOperationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validatorOperationResponse", Namespace="http://facade.validator.cesi.com/", Order=0)]
        public AuthenticationWCF.Validator.validatorOperationResponseBody Body;
        
        public validatorOperationResponse() {
        }
        
        public validatorOperationResponse(AuthenticationWCF.Validator.validatorOperationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class validatorOperationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string message;
        
        public validatorOperationResponseBody() {
        }
        
        public validatorOperationResponseBody(string message) {
            this.message = message;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ValidatorEndpointChannel : AuthenticationWCF.Validator.ValidatorEndpoint, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ValidatorEndpointClient : System.ServiceModel.ClientBase<AuthenticationWCF.Validator.ValidatorEndpoint>, AuthenticationWCF.Validator.ValidatorEndpoint {
        
        public ValidatorEndpointClient() {
        }
        
        public ValidatorEndpointClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ValidatorEndpointClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidatorEndpointClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidatorEndpointClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AuthenticationWCF.Validator.validatorOperationResponse AuthenticationWCF.Validator.ValidatorEndpoint.validatorOperation(AuthenticationWCF.Validator.validatorOperationRequest request) {
            return base.Channel.validatorOperation(request);
        }
        
        public string validatorOperation(string msg) {
            AuthenticationWCF.Validator.validatorOperationRequest inValue = new AuthenticationWCF.Validator.validatorOperationRequest();
            inValue.Body = new AuthenticationWCF.Validator.validatorOperationRequestBody();
            inValue.Body.msg = msg;
            AuthenticationWCF.Validator.validatorOperationResponse retVal = ((AuthenticationWCF.Validator.ValidatorEndpoint)(this)).validatorOperation(inValue);
            return retVal.Body.message;
        }
    }
}
