//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeavyClient.WCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCF.IDecryptorService")]
    public interface IDecryptorService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDecryptorService/m_service", ReplyAction="http://tempuri.org/IDecryptorService/m_serviceResponse")]
        string m_service(string msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDecryptorService/DecryptAsyncMethod", ReplyAction="http://tempuri.org/IDecryptorService/DecryptAsyncMethodResponse")]
        string DecryptAsyncMethod(string msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDecryptorService/java", ReplyAction="http://tempuri.org/IDecryptorService/javaResponse")]
        string java(string msg);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDecryptorServiceChannel : HeavyClient.WCF.IDecryptorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DecryptorServiceClient : System.ServiceModel.ClientBase<HeavyClient.WCF.IDecryptorService>, HeavyClient.WCF.IDecryptorService {
        
        public DecryptorServiceClient() {
        }
        
        public DecryptorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DecryptorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DecryptorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DecryptorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string m_service(string msg) {
            return base.Channel.m_service(msg);
        }
        
        public string DecryptAsyncMethod(string msg) {
            return base.Channel.DecryptAsyncMethod(msg);
        }
        
        public string java(string msg) {
            return base.Channel.java(msg);
        }
    }
}
